async function main() {
  try {
  } catch (error) {
    console.error(error)
  }
}

await main()
console.log("done")
